name: ci
on: [pull_request]

jobs: 
  build:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with: 
        node-version: 22.5.x
      
    - name: Install Dependencies
      uses: npm install

    - name: Run Typecheck
      uses: npm run typecheck

    - name: Run Build
      uses: npm run build